pheno_predict_map = {
    "sample":          "sample_id",
    "HGVS":            "hgvs",
    "CHROM":           "chrom",
    "POS":             "\"POS\"",
    "GENE":            "\"GENE\"",
    "ALTGENE":         "\"ALTGENE\"",
    "ID":              "\"rsID\"",
    "types":           "types",
    "QUAL":            "qual",
    "DEPTH":           "depth",
    "mapquality":      "mapquality",
    "INHERITANCE":     "inheritance",
    "samtools_geno":   "samtools",
    "gatk_geno":       "gatk",
    "unbalance":       "unbalance",
    "consequence":     "consequence",
    "impact":          "impact",
    "clin_sign":       "clin_sign",
    "strand":          "strand",
    "refseq":          "refseq",
    "hgmd":            "hgmd",
    "num_exon":        "exone",
    "num_intron":      "intron",
    "HGVS_c":          "hgvs_c",
    "HGVS_p":          "hgvs_p",
    "CDS_position":    "cds_position",
    "amino_acids":     "amino_acids",
    "codons":          "codons",
    "variation_cosmic": "variation_cosmic",
    "sift":            "sift",
    "polyphen":        "polyphen",
    "decisionmaf":     "decisionmaf",
    "decisionINFO":    "\"decisionINFO\"",
    "GMAF":            "\"GMAF\"",
    "ExAC_MAF":        "\"ExAC_MAF\"",
    "MAX_MAF":         "\"MAX_MAF\"",
    "Adj_MAF":         "\"Adj_MAF\"",
    "AFR_MAF":         "\"AFR_MAF\"",
    "AMR_MAF":         "\"AMR_MAF\"",
    "EAS_MAF":         "\"EAS_MAF\"",
    "EUR_MAF":         "\"EUR_MAF\"",
    "SAS_MAF":         "\"SAS_MAF\"",
    "AA_MAF":          "\"AA_MAF\"",
    "EA_MAF":          "\"EA_MAF\"",
    "pubmed":          "pubmed",
    "hgmd_mutation":   "hgmd_mutation",
    "hgmd_function":   "hgmd_function",
    "hgmd_phenotype":  "hgmd_phenotype",
    "hgmd_pubmed":     "hgmd_pubmed",
    "probsanger":      "probsanger",
    "probcontaminazione": "probcontaminazione",
    "clinvar_MedGen_id": "\"clinvar_MedGen_id\"",
    "clinvar_OMIM_id": "\"clinvar_OMIM_id\"",
    "clinvar_Orphanet_id": "\"clinvar_Orphanet_id\"",
    "clinvar_clnsig": "clinvar_clnsig",
    "clinvar_review": "clinvar_review",
    "gnomAD_exomes_POPMAX_AF": "\"gnomAD_exomes_POPMAX_AF\"",
    "gnomAD_exomes_POPMAX_nhomalt": "\"gnomAD_exomes_POPMAX_nhomalt\"",
    "gnomAD_exomes_controls_AF": "\"gnomAD_exomes_controls_AF\"",
    "gnomAD_exomes_controls_nhomalt": "\"gnomAD_exomes_controls_nhomalt\"",
    "gnomAD_genomes_controls_nhomalt": "\"gnomAD_genomes_controls_nhomalt\"",
    "gnomAD_genomes_POPMAX_AF": "\"gnomAD_genomes_POPMAX_AF\"",
    "gnomAD_genomes_POPMAX_nhomalt": "\"gnomAD_genomes_POPMAX_nhomalt\"",
    "gnomAD_genomes_controls_POPMAX_AF": "\"gnomAD_genomes_controls_POPMAX_AF\"",
    "gnomAD_genomes_controls_POPMAX_nhomalt": "\"gnomAD_genomes_controls_POPMAX_nhomalt\"",
    "gnomAD_exomes_controls_AC": "\"gnomAD_exomes_controls_AC\"",
    "gnomAD_genomes_controls_AC": "\"gnomAD_genomes_controls_AC\""

}



other_annot_map = {
    "sample": "sample_id",
    "HGVS": "hgvs",
    "CHROM": "chrom",
    "POS": "\"POS\"",
    "GENE": "\"GENE\"",
    "ID": "\"rsID\"",
    "CADD_rankscore": "\"CADD_rankscore\"",
    "DANN_rankscore": "\"DANN_rankscore\"", 
    "EigenPC_rankscore": "\"EigenPC_rankscore\"",
    "FATHMM_rankscore": "\"FATHMM_rankscore\"",
    "FATHMM_pred": "\"FATHMM_pred\"",
    "GERP_rankscore": "\"GERP_rankscore\"",
    "Interpro_domain": "\"Interpro_domain\"",
    "LRT_rankscore": "\"LRT_rankscore\"",
    "LRT_pred": "\"LRT_pred\"",
    "MCAP_pred": "\"MCAP_pred\"",
    "MetaLR_pred": "\"MetaLR_pred\"",
    "MetaLR_rankscore": "\"MetaLR_rankscore\"",
    "MetaSVM_pred": "\"MetaSVM_pred\"",
    "MetaSVM_rankscore": "\"MetaSVM_rankscore\"",
    "MutPred_rankscore": "\"MutPred_rankscore\"",
    "MutationAssessor_pred": "\"MutationAssessor_pred\"",
    "MutationAssessor_rankscore": "\"MutationAssessor_rankscore\"",
    "MutationTaster_rankscore": "\"MutationTaster_rankscore\"",
    "MutationTaster_pred": "\"MutationTaster_pred\"",
    "PROVEAN_rankscore": "\"PROVEAN_rankscore\"",
    "PROVEAN_pred": "\"PROVEAN_pred\"",
    "Polyphen2HDIV_pred": "\"Polyphen2HDIV_pred\"",
    "Polyphen2HDIV_rankscore": "\"Polyphen2HDIV_rankscore\"",
    "Polyphen2HVAR_pred": "\"Polyphen2HVAR_pred\"",
    "Polyphen2HVAR_rankscore": "\"Polyphen2HVAR_rankscore\"",
    "REVEL_rankscore": "\"REVEL_rankscore\"",
    "SIFT_rankscore": "\"SIFT_rankscore\"",
    "SIFT_pred": "\"SIFT_pred\"",
    "SiPhy29way_rankscore": "\"SiPhy29way_rankscore\"",
    "VEST3_rankscore": "\"VEST3_rankscore\"",
    "clinvar_clnsig": "clinvar_clnsig",
    "fathmmMKL_pred": "\"fathmmMKL_pred\"",
    "phastCons100way_rankscore": "\"phastCons100way_rankscore\"",
    "phastCons20way_rankscore": "\"phastCons20way_rankscore\"",
    "phyloP100way_rankscore": "\"phyloP100way_rankscore\"",
    "phyloP20way_rankscore": "\"phyloP20way_rankscore\"",
    "ada_score": "ada_score",
    "rf_score": "rf_score"
}



pindel_map = {
    "sample_id": "sample_id",
    "hgvs": "hgvs",
    "chrom": "chrom",
    "GENE": "\"GENE\"",
    "exone": "exone",
    "strand": "strand",
    "refseq": "refseq",
    "ABBERATION": "\"ABBERATION\"",
    "NUMBER_OF_TARGETS": "\"NUMBER_OF_TARGETS\"",
    "REGION_COV": "\"REGION_COV\"",
    "AVG_TOTAL_COV": "\"AVG_TOTAL_COV\"",
    "AVG_GENE_COV": "\"AVG_GENE_COV\"",
    "NORMALIZED_TOTAL": "\"NORMALIZED_TOTAL\"",
    "NORMALIZED_GENE": "\"NORMALIZED_GENE\"",
    "AUTO_RATIO": "\"AUTO_RATIO\"",
    "AUTO_ZSCORE": "\"AUTO_ZSCORE\"",
    "verdict": "verdict",
    "CNVHGVS": "\"CNVHGVS\""
}



genestatcov_map = {
    
    "sample_id": "sample_id",
    "GENE": "GENE",
    "strand": "strand",
    #"transcript": "#transcript",
    "refseq": "refseq",
    "hgmd": "hgmd",
    "exone":"exone",
    "chrm":"chrm",
    "exone_start":"exone_start",
    "exone_end":"exone_end",
    "start_buco":"start_buco",
    "end_buco":"end_buco",
    "len_gene":"len_gene",
    "len_exone":"len_exone",
    "buco_exone":"buco_exone",
    "note":"note",
    "buco_gene":"buco_gene",
    "perc_exone":"perc_exone",
    "perc_gene":"perc_gene",
    "cov_mean":"cov_mean",
    "variante":"variante"

}




checklist_map = {
    
}